### ISSUE TITLE
Structure of this repo

### ISSUE THREAD

**Issue by PF4Public** [ungoogled-software/contrib#1]
We cannot simply bunch everything in the top-level folder, right? Therefore I propose the following structure to establish it from the beginning.

Starting from the top
* **README.md** — Has the already-written introduction and the list of all topic-folders with active links with a brief description of what one finds there
* _Topic_folder_ — We need to sort and categorise contributions based on their nature, I think. I suggest, for example:
* **Fixes** — Some fixes, which are targeted at specific use-cases, not applicable generally in other repos
  * **README.md** — Each level has its own **README.md** with a list of all the contributions at that level
  * _a_single_file_ — If a contribution consists of a single file, it stays on its own and has a detailed enough description in a corresponding **README.md** at this level (the one mentioned above)
  * _a_folder_with_descriptive_name_ — Is used if a contribution needs more, than a single file
    * **README.md** — A detailed description of this contribution, usage examples, etc. License maybe.
    * _file1_
    * _file2_
    * _subfolder_if_needed_
* **Features** — Some ideas and implementations
  * Same structure here
* **Scripts** — Various scripts 
  * Same structure here
* What else do we need?
  * Suggestions — welcome!

When we finally come to the agreement, if nobody minds of-course, I will take the liberty to create a pull request with the agreed-upon structure.

**Comment by PF4Public** [comment]
Otherwise we end up bunching everything up: #2

**Comment by Eloston** [comment]
Your argument has merit, but I think there are two problems with the proposal:

### 1. The intent of contrib

contrib is essentially a box for UGC. UGC is complex and messy, and is at least difficult to conform to any one data structure (e.g. a file system tree). As such, anything that doesn't really fit in the data structure creates friction in the user's ability to contribute (e.g. where should I put these files?) and ability to retrieve (e.g. where would I find files for my usecase?).

While a more unstructured approach reduces friction for contributions, it isn't immediately clear how that reduces friction for retrieval. I think this is solved in two ways:

1. Users who have contributed can share their contributions to others who need it
2. Users can browse through the repo themselves or use a search function (e.g. GitHub has a grep-like feature built-in) to find what they need.

The major downside of an unstructured approach is it does not scale well as the repo grows. A more rigorous structure ameliorates the problem, but it does not solve it.

### 2. The use-cases of contrib

The more challenging problem is understanding how people will use contrib. It is much harder to predict how a user-centric system will evolve over time (as opposed to projects like ungoogled-chromium, which are guided by developers who have a specific vision in mind). I believe that if a structure will be useful for contrib, it won't become apparent until people have started using it more. Otherwise, we will be enforcing a structure based on our own experiences and biases that may not apply to our users.

---

In either case, I don't see an immediate cause for action because contrib is pretty much empty. I think we should hold off on this proposal until contrib starts being used and useful.

**Comment by InnovativeInventor** [comment]
> Otherwise we end up bunching everything up: #2

Just saw this issue @PF4Public thanks for the input/feedback, really good point there (although it doesn't seem like this repo is in danger of being overcrowded too soon). I feel that the # of organizational folders should never be more than the number of actual documents in the repo at any given time . . .

> In either case, I don't see an immediate cause for action because contrib is pretty much empty. I think we should hold off on this proposal until contrib starts being used and useful.

Yep, I agree, although changing from `/docker` is probably a good idea (as @Eloston  pointed out in the PR).
